[font]
size = 14.0

[font.normal]
family = "CaskaydiaCove NF"
style = "Regular"

[window.padding]
x = 7
y = 5

[window]
# opacity = 0.9
startup_mode = "Maximized"
dynamic_title = true
decorations = "None"

[terminal]
shell = { program = "wsl.exe", args = ["-d", "Ubuntu", "--cd", "~"] }

[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1A1D23"
foreground = "#a9b1d6"


---------------------



[colors.primary]
background = "0x1b1e28"
foreground = "0xa6accd"

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.search.matches]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.search.focused_match]
foreground = "0x1b1e28"
background = "0xadd7ff"

[colors.selection]
text = "CellForeground"
background = "0x303340"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.normal]
black = "0x1b1e28"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0x89ddff"
magenta = "0xfcc5e9"
cyan = "0xadd7ff"
white = "0xffffff"

[colors.bright]
black = "0xa6accd"
red = "0xd0679d"
green = "0x5de4c7"
yellow = "0xfffac2"
blue = "0xadd7ff"
magenta = "0xfae4fc"
cyan = "0x89ddff"
white = "0xffffff"
